function CPtextdisplaybox(Text,title)

% Custom text display box for CellProfiler, with a slider if the text
% becomes too long to fit into a small window.

helpFig = figure;
set(helpFig,'NumberTitle','off');
set(helpFig,'name', title);
set(helpFig,'units','characters','color',[0.7 0.7 0.9]);
helpFigPos = get(helpFig,'position');
set(helpFig,'position',[helpFigPos(1),helpFigPos(2),87,helpFigPos(4)]);
%%% Label we attach to figures (as UserData) so we know they are ours
userData.Application = 'CellProfiler';
set(helpFig,'UserData',userData);

helpUI = uicontrol(...
    'Parent',helpFig,...
    'Enable','inactive',...
    'Units','characters',...
    'HorizontalAlignment','left',...
    'Max',2,...
    'Min',0,...
    'Position',[1 1 helpFigPos(3) helpFigPos(4)],...
    'String',Text,...
    'BackgroundColor',[0.7 0.7 0.9],...
    'Style','text');
outstring = textwrap(helpUI,{Text});
set(helpUI,'position',[1 1.5+(27-length(outstring))*1.09 80 length(outstring)*1.09]);
if(length(outstring) > 27),
    helpUIPosition = get(helpUI,'position');
    helpScrollCallback = ['set(',num2str(helpUI,'%.13f'),',''position'',[', ...
        num2str(helpUIPosition(1)),' ',num2str(helpUIPosition(2)),'+get(gcbo,''max'')-get(gcbo,''value'') ', num2str(helpUIPosition(3)), ...
        ' ', num2str(helpUIPosition(4)),'])'];

    helpScrollUI = uicontrol(...
        'Parent',helpFig,...
        'Callback',helpScrollCallback,...
        'Units','characters',...
        'Visible', 'on',...
        'BackgroundColor',[0.7 0.7 0.9],...
        'Style', 'slider',...
        'SliderStep', [.1 .6],...
        'Position',[81 1 4 30]);
    set(helpScrollUI,'max',(length(outstring)-27)*1.09);
    set(helpScrollUI,'value',(length(outstring)-27)*1.09);
end