function h = CPimagesc(Image,handles)

% CellProfiler is distributed under the GNU General Public License.
% See the accompanying file LICENSE for details.
%
% Developed by the Whitehead Institute for Biomedical Research.
% Copyright 2003,2004,2005.
%
% Please see the AUTHORS file for credits.
%
% Website: http://www.cellprofiler.org
%
% $Revision$

%%% Displays the image.
h = imagesc(Image);
%%% Embeds the Image tool submenu so that it appears when the user clicks
%%% on the image. 
set(h,'ButtonDownFcn','CPimagetool');

%%% Sets the user's preference for font size, which should affect tick
%%% labels and current and future titles.
set(gca,'fontsize',handles.Preferences.FontSize)

%%% Applies the user's choice for colormap.
if ndims(Image) == 2
    colormap(handles.Preferences.IntensityColorMap);
end

ImageHandles = findobj(gcf,'Type','Image');
FigUserData = get(gcf,'Userdata');

FigHandle = gcf;
Font = handles.Preferences.FontSize;
 
if isempty(findobj(gcf,'tag','ToggleColorR'))
    ToggleColorR = ...
        ['ImageHandles = findobj(gcf,''Type'',''Image'');' ...
            'for i = length(ImageHandles):-1:1,' ...
                'if size(size(get(ImageHandles(i),''CData'')),2)~=3,' ...
                    'ImageHandles(i)=[];' ...
                'end;' ...
            'end;' ...
            'if ~isempty(ImageHandles),' ...
                'AllData=get(ImageHandles,''CData'');' ...
                'ImageHandles = num2cell(ImageHandles);' ...
                'if ~iscell(AllData),' ...
                    'AllData={AllData};' ...
                'end;' ...
                'button=findobj(gcf,''tag'',''ToggleColorR'');' ...
                'for i = 1:length(AllData),' ...
                  'tempdata{i}=AllData{i}(:,:,1);' ...
                'end;' ...
                'for i = 1:length(AllData),' ...
                    'data=AllData{i};' ...
                    'if get(button,''value'')==0,' ...
                        'set(button,''UserData'',tempdata);' ...
                        'data(:,:,1)=0;' ...
                        'set(ImageHandles{i},''CData'',data);' ...
                    'else,' ...
                        'tempdata=get(button,''UserData'');' ...
                        'if ~iscell(tempdata),' ...
                        'tempdata={tempdata};' ...
                        'end;' ...
                        'data(:,:,1)=tempdata{i};' ...
                        'AllData{i}=data;' ...
                        'set(ImageHandles{i},''CData'',data);' ...
                    'end;' ...
                'end;' ...
            'end;' ...
        'clear data AllData button ImageHandles i tempdata;'];
    uicontrol('Style', 'checkbox', ...
        'Units','normalized',...
        'Position', [.93 .6 .06 .04], ...
        'Callback', ToggleColorR, 'parent',FigHandle, ...
        'FontSize',Font,'BackgroundColor',[.7,.7,.9],'min',0,...
        'max',1,'value',1,'tag','ToggleColorR','string','R');
end

if isempty(findobj(gcf,'tag','ToggleColorG'))
    ToggleColorG = ...
        ['ImageHandles = findobj(gcf,''Type'',''Image'');' ...
            'for i = length(ImageHandles):-1:1,' ...
                'if size(size(get(ImageHandles(i),''CData'')),2)~=3,' ...
                    'ImageHandles(i)=[];' ...
                'end;' ...
            'end;' ...
            'if ~isempty(ImageHandles),' ...
                'AllData=get(ImageHandles,''CData'');' ...
                'ImageHandles = num2cell(ImageHandles);' ...
                'if ~iscell(AllData),' ...
                    'AllData={AllData};' ...
                'end;' ...
                'button=findobj(gcf,''tag'',''ToggleColorG'');' ...
                'for i = 1:length(AllData),' ...
                    'tempdata{i}=AllData{i}(:,:,2);' ...
                'end;' ...
                'for i = 1:length(AllData),' ...
                    'data=AllData{i};' ...
                    'if get(button,''value'')==0,' ...
                        'set(button,''UserData'',tempdata);' ...
                        'data(:,:,2)=0;' ...
                        'set(ImageHandles{i},''CData'',data);' ...
                    'else,' ...
                        'tempdata=get(button,''UserData'');' ...
                        'if ~iscell(tempdata),' ...
                            'tempdata={tempdata};' ...
                        'end;' ...
                        'data(:,:,2)=tempdata{i};' ...
                        'AllData{i}=data;' ...
                        'set(ImageHandles{i},''CData'',data);' ...
                    'end;' ...
                'end;' ...
            'end;' ...
            'clear data AllData button ImageHandles i tempdata;'];
    uicontrol('Style', 'checkbox', ...
        'Units','normalized',...
        'Position', [.93 .55 .06 .04], ...
        'Callback', ToggleColorG, 'parent',FigHandle, ...
        'FontSize',Font,'BackgroundColor',[.7,.7,.9],'min',0,...
        'max',1,'value',1,'tag','ToggleColorG','string','G');
end

if isempty(findobj(gcf,'tag','ToggleColorB'))
    ToggleColorB = ...
        ['ImageHandles = findobj(gcf,''Type'',''Image'');' ...
            'for i = length(ImageHandles):-1:1,' ...
                'if size(size(get(ImageHandles(i),''CData'')),2)~=3,' ...
                    'ImageHandles(i)=[];' ...
                'end;' ...
            'end;' ...
            'if ~isempty(ImageHandles),' ...
                'AllData=get(ImageHandles,''CData'');' ...
                'ImageHandles = num2cell(ImageHandles);' ...
                'if ~iscell(AllData),' ...
                    'AllData={AllData};' ...
                'end;' ...
                'button=findobj(gcf,''tag'',''ToggleColorB'');' ...
                'for i = 1:length(AllData),' ...
                    'tempdata{i}=AllData{i}(:,:,3);' ...
                'end;' ...
                'for i = 1:length(AllData),' ...
                    'data=AllData{i};' ...
                    'if get(button,''value'')==0,' ...
                        'set(button,''UserData'',tempdata);' ...
                        'data(:,:,3)=0;' ...
                        'set(ImageHandles{i},''CData'',data);' ...
                    'else,' ...
                        'tempdata=get(button,''UserData'');' ...
                        'if ~iscell(tempdata),' ...
                            'tempdata={tempdata};' ...
                        'end;' ...
                        'data(:,:,3)=tempdata{i};' ...
                        'AllData{i}=data;' ...
                        'set(ImageHandles{i},''CData'',data);' ...
                    'end;' ...
                'end;' ...
            'end;' ...
            'clear data AllData button ImageHandles i tempdata;'];
    uicontrol('Style', 'checkbox', ...
        'Units','normalized',...
        'Position', [.93 .50 .06 .04], ...
        'Callback', ToggleColorB, 'parent',FigHandle, ...
        'FontSize',Font,'BackgroundColor',[.7,.7,.9],'min',0,...
        'max',1,'value',1,'tag','ToggleColorB','string','B');
end

%% The RBG buttons default to being drawn for each individual axes object, 
%% but we delete RGB buttons if there are no color images in the figure
if isfield(FigUserData,'MyHandles')
    for i = length(ImageHandles):-1:1
        NDIM(i) = ndims(get(ImageHandles(i),'CData'));
    end
    if ~any(NDIM == 3)
        delete(findobj(gcf,'Tag','ToggleColorR'))
        delete(findobj(gcf,'Tag','ToggleColorG'))
        delete(findobj(gcf,'Tag','ToggleColorB'))
    end
end