# coding:utf-8

import glob
import os.path

import jinja2
import pkg_resources
import six.moves.urllib.parse
import wx
import wx.html2

import cellprofiler
import cellprofiler.gui.help.content
import cellprofiler.gui.html
import cellprofiler.gui.html.utils
import cellprofiler_core.preferences

CONFIGURE_IMAGES_REF = six.moves.urllib.parse.quote("Configure images")
EXPORTING_RESULTS_REF = six.moves.urllib.parse.quote("Exporting results")
IDENTIFY_FEATUREES_REF = six.moves.urllib.parse.quote("Identifying features")
IN_APP_HELP_REF = six.moves.urllib.parse.quote("Using the help")
MAKING_MEASUREMENTS_REF = six.moves.urllib.parse.quote("Making measurements")
RUNNING_YOUR_PIPELINE_REF = six.moves.urllib.parse.quote("Analyzing your images")
TEST_MODE_REF = six.moves.urllib.parse.quote("Using test mode")
SELECTING_IMAGES_REF = six.moves.urllib.parse.quote("Selecting images")
WELCOME_MAIN_REF = six.moves.urllib.parse.quote("Welcome")

GO_BACK = """<p>Go <a href=help:welcome>back</a> to the welcome screen.</p>"""


EXPORTING_RESULTS_HELP = """\
<!DOCTYPE html>
<html>
<head>
    <title>Exporting results</title>
</head>
<body>
    <p>Writing the measurements generated by CellProfiler is necessary for
    downstream statistical analysis. The most common format for export is the
    <i>spreadsheet</i> which is a table of values. The module
    <b>ExportToSpreadsheet</b> handles the task of writing the measurements
    (for images, objects or both) to a file readable by Excel, or the
    spreadsheet program of your choice.</p>
    <p>For larger assays, involving tens of thousands of images or more, a
    spreadsheet is usually insufficient to handle the massive amounts of data
    generated. A <i>database</i> is a better solution in this case, although
    this requires more computational expertise; the <b>ExportToDatabase</b>
    module is to be used for this task. If this avenue is needed, it is best to
    consult with your information technology department.</p>
    <p>CellProfiler will not save images produce by analysis modules unless
    told to do so. It is often desirable to save the outlines of the objects
    identified; this can is useful as a sanity check of the object
    identification results or for quality control purposes. The
    <b>SaveImages</b> module is used for saving images to a variety of output
    formats; you can specify the nomenclature.</p>
    <p>For more information on these modules and how to configure them for best
    performance, please see the detailed help by selecting the module and
    clicking the <img src="{MODULE_HELP_BUTTON}"> button at the bottom
    of the pipeline panel. You can also find details on various exporting
    options under <i>{USING_YOUR_OUTPUT_REF}</i></p>
    {GO_BACK}
</body>
</html>
""".format(
    **{
        "GO_BACK": GO_BACK,
        "MODULE_HELP_BUTTON": cellprofiler.gui.help.content.MODULE_HELP_BUTTON,
        "USING_YOUR_OUTPUT_REF": cellprofiler.gui.help.content.USING_YOUR_OUTPUT_REF,
    }
)

IDENTIFY_FEATUREES_HELP = """\
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <p>A hallmark of most CellProfiler pipelines is the identification of
    cellular features in your images, whether they are nuclei, organelles or
    something else.</p>
    <table cellpadding="0" width="75%">
        <tr>
            <td valign="top" width="75%">A number of modules are dedicated to
            the purpose of detecting these features; the
            <b>IdentifyPrimaryObjects</b> module is the one that is most
            commonly used. The result of this module is a set of labeled
            <i>objects</i>; we define an object as a collection of connected
            pixels in an image which share the same label. The challenge here
            is to find a combination of settings that best identify the objects
            from the image, a task called <i>segmentation</i>. The typical
            expectation is to end up with one object for each cellular feature
            of interest (for example, each nucleus is assigned to a single
            object in a DNA stained image). If this is not the case, the module
            settings can be adjusted to make it so (or as close as possible).
            In some cases, image processing modules must be used beforehand to
            transform the image so it is more amenable to object
            detection.</td>
            <td align="center" width="25%"><img height="225" src=
            "memory:image_to_object_dataflow.png" width="254"></td>
        </tr>
    </table>
    <p>In brief, the workflow of finding objects using this module is to do the
    following:</p>
    <ul>
        <li><i>Distinguish the foreground from background:</i> The foreground
        is defined as that part of the image which contains the features of
        interest, as opposed to the <i>background</i> which does not. The
        module assumes that the foreground is brighter than the background,
        which is the case for fluorescence images; for other types of images,
        other modules can be used to first invert the image, turning dark
        regions into bright regions and vice versa.</li>
        <li><i>Identify the objects in each foreground region:</i> Each
        foreground region may contain multiple objects of interest (for
        example, touching nuclei in a DNA stained image). Recognizing the
        presence of these objects is the objective of this step.</li>
        <li><i>Splitting clusters of objects:</i> If objects are touching each
        other, the final step is to separate them in a way that reflects the
        actual boundaries as much as possible. This process is referred to as
        "declumping."</li>
    </ul>The module also contains additional settings for filtering the results
    of this process on the basis of size, location, etc. to get the final
    object set. At this point, the objects are ready for measurements to be
    made, or for further manipulations as a means of extracting other features.
    <p></p>
    <p>Other modules are able to take the results of this module and use them
    in combination with additional images (like
    <b>IdentifySecondaryObjects</b>) or other objects (like
    <b>IdentifyTertiaryObjects</b>) to define yet more objects.</p>
    <p>For more information on these identification modules work and how to
    configure them for best performance, please see the detailed help by
    selecting the <b>IdentifyPrimaryObjects</b> module and clicking the
    <img src="{MODULE_HELP_BUTTON}">&nbsp; button at the bottom of the
    pipeline panel.</p>
    {GO_BACK}
</body>
</html>
""".format(
    **{
        "GO_BACK": GO_BACK,
        "MODULE_HELP_BUTTON": cellprofiler.gui.help.content.MODULE_HELP_BUTTON,
    }
)

IN_APP_HELP = """\
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <p>In addition to the Help menu in the main CellProfiler window, there are <img src="{MODULE_HELP_BUTTON}">
    buttons containing more specific documentation for using CellProfiler. Clicking the "?" button near the pipeline 
    window will show information about the selected module within the pipeline, whereas clicking the 
    <img src="{MODULE_HELP_BUTTON}"> button to the right of each of the module setting displays help for that 
    particular setting.</p>
    {GO_BACK}
</body>
</html>
""".format(
    **{
        "GO_BACK": GO_BACK,
        "MODULE_HELP_BUTTON": cellprofiler.gui.help.content.MODULE_HELP_BUTTON,
    }
)

MAKING_MEASUREMENTS_HELP = """\
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <p>In most cases, the reason for identifying image features is to make
    measurements on them. CellProfiler has a number of modules dedicated to
    calculating measurements of various types, on both images and objects;
    these are accessible by clicking the <img src=
    "{MODULE_ADD_BUTTON}">&nbsp;button (located underneath the pipeline
    panel)</p>
    <p>Below is a list of measurement categories; these is not meant to be
    comprehensive, but are sufficient for most assays:</p>
    <table border="1" cellpadding="10">
        <tr align="center" bgcolor="#555555">
            <th><font color="#FFFFFF"><b>Measurement</b></font></th>
            <th><font color="#FFFFFF"><b>Description</b></font></th>
            <th><font color="#FFFFFF"><b>Relevant modules</b></font></th>
        </tr>
        <tr align="center">
            <td><i>Count</i></td>
            <td>The number of objects in an image.</td>
            <td>All modules which produce a new set of objects, such as
            <b>IdentifyPrimaryObjects</b></td>
        </tr>
        <tr align="center">
            <td><i>Location</i></td>
            <td>The (x,y) coordinates of each object, which can be of interest
            in time-lapse imaging.</td>
            <td>All modules which produce a new set of objects</td>
        </tr>
        <tr align="center">
            <td><i>Morphology</i></td>
            <td>Quantities defining the geometry of the object, as defined by
            its external boundary. This includes quantities like area,
            perimeter, etc.</td>
            <td>
            <b>MeasureImageAreaOccupied</b>,<b>MeasureObjectSizeShape</b></td>
        </tr>
        <tr align="center">
            <td><i>Intensity</i></td>
            <td>In fluorescence assays, the intensity of a pixel is related to
            the substance labeled with a fluorescence marker at that location.
            The maximal, minimal, mean, and integrated (total) intensity of
            each marker can be measured as well as correlations in intensity
            between channels.</td>
            <td><b>MeasureObjectIntensity</b>, <b>MeasureImageIntensity</b>,
            <b>MeasureObjectRadialDistribution</b>,
            <b>MeasureColocalization</b></td>
        </tr>
        <tr align="center">
            <td><i>Texture</i></td>
            <td>These quantities characterize spatial smoothness and regularity
            across an object, and are often useful for characterizing the fine
            patterns of localization.</td>
            <td><b>MeasureTexture</b></td>
        </tr>
        <tr align="center">
            <td><i>Clustering</i></td>
            <td>Spatial relationships can be characterized by adjacency
            descriptors, such as the number of neighboring objects, the percent
            of the perimeter touching neighbor objects, etc.</td>
            <td><b>MeasureObjectNeighbors</b></td>
        </tr>
    </table>
    <p>For more information on these modules and how to configure them for best
    performance, please see the detailed help by selecting the module and
    clicking the <img src="{MODULE_HELP_BUTTON}">&nbsp; button at the bottom of
    the pipeline panel. You can also find details on measurement nomenclature
    when exporting under <i>{MEASUREMENT_NAMING_HELP}</i></p>
    {GO_BACK}
</body>
</html>
""".format(
    **{
        "GO_BACK": GO_BACK,
        "MEASUREMENT_NAMING_HELP": cellprofiler.gui.help.content.MEASUREMENT_NAMING_HELP,
        "MODULE_ADD_BUTTON": cellprofiler.gui.help.content.MODULE_ADD_BUTTON,
        "MODULE_HELP_BUTTON": cellprofiler.gui.help.content.MODULE_HELP_BUTTON,
    }
)

RUNNING_YOUR_PIPELINE_HELP = """\
<!DOCTYPE html>
<html>
<head>
    <title>Analyzing your images</title>
</head>
<body>
    {RUNNING_YOUR_PIPELINE_CONTENT}
    {GO_BACK}
</body>
""".format(
    **{
        "GO_BACK": GO_BACK,
        "RUNNING_YOUR_PIPELINE_CONTENT": cellprofiler.gui.html.utils.rst_to_html_fragment(
            cellprofiler.gui.help.content.read_content("pipelines_running.rst")
        ),
    }
)

TEST_MODE_HELP = """\
<!DOCTYPE html>
<html>
<head>
    <title>Using test mode</title>
</head>
<body>
    {TEST_MODE_CONTENT}
    {GO_BACK}
</body>
""".format(
    **{
        "GO_BACK": GO_BACK,
        "TEST_MODE_CONTENT": cellprofiler.gui.html.utils.rst_to_html_fragment(
            cellprofiler.gui.help.content.read_content("navigation_test_menu.rst")
        ),
    }
)



class Welcome(wx.Frame):
    def __init__(self, parent):
        super(Welcome, self).__init__(
            parent,
            name="WelcomeScreenFrame",
            size=(640, 480),
            title="Welcome to CellProfiler",
        )

        self.SetSizer(wx.BoxSizer())

        self.SetIcon(cellprofiler.gui.get_cp_icon())

        self.Bind(wx.EVT_CLOSE, self.__on_close)
        self.content = wx.html2.WebView.New(self)
        self.content.EnableContextMenu(False)
        self.__display_welcome()

        self.content.Bind(wx.html2.EVT_WEBVIEW_NAVIGATING, self._on_navigate)

        self.GetSizer().Add(self.content, 1, wx.EXPAND)

        self.Layout()

        self.href_to_help = {
            "configureimages": "html/configure_images_help.html",
            "exportingresults": EXPORTING_RESULTS_HELP,
            "identifyfeatures": IDENTIFY_FEATUREES_HELP,
            "inapphelp": "html/in_app_help.html",
            "makingmeasurements": MAKING_MEASUREMENTS_HELP,
            RUNNING_YOUR_PIPELINE_REF: RUNNING_YOUR_PIPELINE_HELP,
            TEST_MODE_REF: TEST_MODE_HELP,
            "selectingimages": "html/selecting_images_help.html",
            "gettingstarted": "html/getting_started.html",
            "welcome": "html/welcome.html",
        }

    def __display_welcome(self):
        with open(os.path.join(os.path.dirname(__file__), "html/welcome.html")) as fp:
            template = jinja2.Template(fp.read())
            self.content.SetPage(html=template.render(
                MANUAL_URL=cellprofiler.gui.help.content.MANUAL_URL,
                WELCOME_MANUAL=os.path.abspath(cellprofiler.gui.help.content.image_resource("welcome_manual.png")),
                WELCOME_FORUM=os.path.abspath(cellprofiler.gui.help.content.image_resource("welcome_forum.png")),
                WELCOME_PIPELINE=os.path.abspath(cellprofiler.gui.help.content.image_resource("welcome_pipeline.png")),
                WELCOME_TUTORIALS=os.path.abspath(cellprofiler.gui.help.content.image_resource("welcome_tutorial.png")),
                WELCOME_EXAMPLES=os.path.abspath(cellprofiler.gui.help.content.image_resource("welcome_examples.png")),
                WELCOME_TOUR=os.path.abspath(cellprofiler.gui.help.content.image_resource("welcome_new.png")),
                WELCOME_HELP=os.path.abspath(cellprofiler.gui.help.content.image_resource("welcome_help.png")),
            ),
                                 baseUrl="welcome")

    @staticmethod
    def __on_close(event):
        event.EventObject.Hide()

        event.Veto()


    def _on_navigate(self, event):
        href = event.URL
        print("Intercepted ", href)
        if href.startswith("help:"):
            self.__display_help(href[5:])
        elif href.startswith("loadexample:"):
            self.__load_example_pipeline(href[12:])
        elif href.startswith("pref:"):
            self.__set_startup_blurb()
        elif href.startswith("http"):
            wx.LaunchDefaultBrowser(href)
        event.Veto()

    def __display_help(self, href):
        if href == "welcome":
            self.__display_welcome()
            return
        html_path = self.href_to_help[href]
        with open(os.path.join(os.path.dirname(__file__), html_path)) as fp:
            template = jinja2.Template(fp.read())
            self.content.SetPage(html=template.render(
                GO_BACK=GO_BACK,
                MODULE_HELP_BUTTON=os.path.abspath(cellprofiler.gui.help.content.MODULE_HELP_BUTTON),
                SELECTING_IMAGES_REF="help",
                CONFIGURE_IMAGES_CONTENT=cellprofiler.gui.html.utils.rst_to_html_fragment(
                    cellprofiler.gui.help.content.read_content("projects_configure_images.rst")),
                SELECTING_IMAGES_HELP="help",
                IDENTIFY_FEATUREES_REF="help",
                MAKING_MEASUREMENTS_REF="help",
                EXPORTING_RESULTS_REF="help",
            ), baseUrl=html_path)

        #self.content.SetPage(html_str)

    @staticmethod
    def __load_example_pipeline(example_name):
        example_dir = pkg_resources.resource_filename(
            "cellprofiler", os.path.join("data", "examples", example_name)
        )

        pipeline_pathname = os.path.join(
            example_dir, "{:s}.cppipe".format(example_name)
        )

        images_dir = os.path.join(example_dir, "images")

        try:

            def load(pathname=pipeline_pathname):
                pipeline = wx.GetApp().frame.pipeline
                pipeline.load(pathname)
                pipeline.add_pathnames_to_file_list(
                    glob.glob(os.path.join(images_dir, "*"))
                )

                wx.MessageBox(
                    'Now that you have loaded an example pipeline, press the "Analyze images" button to access and'
                    " process a small image set from the CellProfiler website so you can see how CellProfiler works.",
                    "",
                    wx.ICON_INFORMATION,
                )

            wx.CallAfter(load)
        except:
            wx.MessageBox(
                "CellProfiler was unable to load {}".format(pipeline_pathname),
                "Error loading pipeline",
                style=wx.OK | wx.ICON_ERROR,
            )

    def __set_startup_blurb(self):
        cellprofiler_core.preferences.set_startup_blurb(False)

        parent = self.GetParent()

        while parent is not None:
            if parent.Name == "WelcomeScreenFrame":
                parent.Close()
                break
            parent = parent.Parent
