function SpliceAviMovie

Pathname = pwd;

NewFilename = 'GOOD_GFPHistone2noIntroLINEMOV.avi';

Filenames = {'GOOD_GFPHistone2noIntro_1_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_2_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_3_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_4_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_5_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_6_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_7_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_8_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_9_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_10_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_11_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_12_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_13_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_14_1LINEMOV.avi'...
    'GOOD_GFPHistone2noIntro_15_1LINEMOV.avi'};

NewFileAndPathName = fullfile(Pathname,NewFilename);
NewAviMovie = avifile(NewFileAndPathName);
NumMovies = length(Filenames);

for i = 1:NumMovies
    LoadedRawImages = aviread(fullfile(Pathname,char(Filenames(i))));
    try NewAviMovie = addframe(NewAviMovie,LoadedRawImages);
    catch error(['Problem encountered during save of ',NewFileAndPathName])
        return
    end
    Status = ['Added frames from the movie: ', char(Filenames(i))]
end

Status = ['Writing the spliced movie: ', NewFilename]
try NewAviMovie = close(NewAviMovie)
    catch error(['Problem encountered during save of ',NewFileAndPathName])
end