#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.2 on Thu Sep 25 15:10:53 2008

import wx
from CellProfiler.CellProfilerGUI.CPFrame import CPFrame

class CellProfilerApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        Frame = CPFrame(None, -1, "")
        self.SetTopWindow(Frame)
        Frame.Show()
        return 1

# end of class CellProfilerApp

if __name__ == "__main__":
    CellProfilerApp = CellProfilerApp(0)
    CellProfilerApp.MainLoop()
