jobs:
  create_release:
    name: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        uses: actions/create-release@v1
        with:
          draft: true
          prerelease: true
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
name: create-release
on:
  push:
    tags:
      - "v*"
