name: Deploy Packages to PyPI
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Upload Library
      working-directory: ${{ github.workspace }}/src/subpackages/library/
      run: |
        python -m build
        twine upload dist/*
    - name: Upload Core
      working-directory: ${{ github.workspace }}/src/subpackages/core/
      run: |
        python -m build
        twine upload dist/*
    - name: Upload Library
      working-directory: ${{ github.workspace }}/src/frontend/
      run: |
        python -m build
        twine upload dist/*
on:
  release:
    types: [created]
